### ISSUE TITLE
[feature request] support for external downloader

### ISSUE THREAD

**Issue by Salah242222** [ErrorFlynn/ytdlp-interface#226]
I would like this app to support downloading through external downloaders' like for example : aria2c

Github Page : https://github.com/aria2/aria2

**Comment by ErrorFlynn** [comment]
The program already has partial support for aria2c. I say "partial", because you have to manually put aria2c.exe in the program folder, and you have to use a custom argument (for example `--downloader aria2c --downloader-args aria2c:"-x 8"`). Also, there's a chance that download progress might not be indicated properly for some files (I don't remember if I fixed that or not), but the download will always work.

I don't know if I will implement explicit support for aria2c (so you don't need to use a custom argument), I'll think about it.

**Comment by Salah242222** [comment]
yeah right now I'm doing that, and you are right about the download progress on some files, you didn't fix it, i saw it multiple times but you can see it from the log tab

**Comment by ErrorFlynn** [comment]
OK, I looked into it, and the case when progress is not indicated is when the download is fragmented. In that case, yt-dlp will say `[hlsnative] Fragment downloads will be delegated to aria2c`, and then the progress text is like this:
`[DL:18MiB][#516367 6.4MiB/7.6MiB(84%)][#f12ae3 6.2MiB/7.5MiB(81%)][#07a9ac 6.0MiB/7.6MiB(79%)][#5785c0 5.6Mi`.
So it just shows the individual progress for a bunch of fragments, not the overall progress for the entire file. All the program can do with that is to either display that text in the output panel (current situation), or display it in the progress bar (I think preferable, will implement for next version).

I also intend to add explicit support for aria2c, so you can set the program to automatically pass the required arguments to yt-dlp, _probably_ in the next version.
